#!/usr/bin/php
<?php

/**
 * This Software is the property of Joerg Rossdeutscher and
 * licensed under GPL v3. See http://www.gnu.org/licenses/gpl-3.0
 *
 *
 * @link      http://www.zeichenwege.de
 * @copyright (C) Joerg Rossdeutscher 2014
 * @author    Joerg Rossdeutscher <joerg.rossdeutscher _AT_ zeichenwege.de>
 */


error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);

require_once __DIR__ . "/lib/fotoschrubber.php";



if( count($argv) != 2 ) die( "Please start with exactly 1 parameter: The folder.\n");

$folder = $argv[1];

if( ! is_dir($folder) ) die( "Parameter is not a folder.\n");

$folder	= realpath($folder);

if( ! is_dir($folder) || $folder=='' ) die( "This should never happen.\n");



$imgFile = new imgFileCollection;
$imgFile->getFilesInFolder( 'imgFile' , $folder , '/^.+\.(JPG|CR2)$/uis' );

$imgFile->renameFiles();
